---
- name: Enable devel repos to get redhat-lsb-core
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled devel
- name: Install redhat-lsb-core
  ansible.builtin.dnf:
    name: redhat-lsb-core
    state: present
